server:
  port: 80

neo4j:
  datasource:
    url: http://127.0.0.1:7474
    username: neo4j
    password: zong

fdfs:
  soTimeout: 1501
  connectTimeout: 601
  thumbImage:
    width: 150
    height: 150
  trackerList:
    - 192.168.3.2:22122
#    - 192.168.1.215:22122
spring.jmx.enabled: false

file.path.head: http://192.168.3.2:80/

